### ISSUE TITLE
Document minimal API token scopes

### ISSUE THREAD

**Issue by kisoku** [pantheon-systems/baryon#5]
Github has a way to limit the authorization scope of each API token you generate.

It would be awesome if you guys could document exactly which scopes Baryon requires in the README

**Comment by spheromak** [comment]
will do, currently we give it the Repo privs and nothing else. 

<img width="574" alt="screenshot 2016-01-26 21 23 01" src="https://cloud.githubusercontent.com/assets/48340/12604730/1bd9d192-c473-11e5-9478-5cc3b3db3823.png">

mostly just cause it has to read private repos.
